# Generated by Django 5.2.8 on 2025-11-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immich_id', models.UUIDField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=200)),
                ('remote_url', models.URLField(blank=True, max_length=500)),
                ('person_face_box', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person', 'photo_date'], name='people_phot_person__3e2cfa_idx')],
            },
        ),
    ]
