# Generated by Django 5.2.8 on 2025-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='age_at_photo_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='age_at_photo_years',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
