# Generated by Django 5.2.9 on 2025-12-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_photo_age_at_photo_months_photo_age_at_photo_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
